#!/bin/bash
# Build script to generate embedded rule headers from JSON files
# Processes all JSON files in rules/converter/ directory

echo "Generating embedded rule headers..."

# Process each JSON file in rules/converter/
for jsonfile in rules/converter/*.json; do
 basename=$(basename "$jsonfile" .json)
 echo "Processing ${basename}.json..."
 xxd -i "$jsonfile" "modules/${basename}_rules.h"
done

# Create master rules.h that includes all rule headers
echo "Creating master rules header..."
cat > modules/rules.h << 'EOF'
// modules/rules.h
// Auto-generated master header that includes all conversion rule data
// Generated by build_rules.sh

#ifndef RULES_H
#define RULES_H

EOF

for jsonfile in rules/converter/*.json; do
 basename=$(basename "$jsonfile" .json)
 echo "#include \"${basename}_rules.h\"" >> modules/rules.h
done

cat >> modules/rules.h << 'EOF'

#endif // RULES_H
EOF

echo ""
echo "Done! Generated headers:"
ls -1 modules/*_rules.h modules/rules.h

echo ""
echo "Now compile with: gcc -DUSE_EMBEDDED_RULES ccal.c modules/converter.c -o ccal.exe"
