@echo off
REM Build script to generate embedded rule headers from JSON files
REM Processes all JSON files in rules/converter/ directory

echo Generating embedded rule headers...

REM Process each JSON file in rules/converter/
for %%f in (rules\converter\*.json) do (
    echo Processing %%~nf.json...
    xxd -i rules\converter\%%~nf.json modules\%%~nf_rules.h
)

REM Create master rules.h that includes all rule headers
echo Creating master rules header...
(
    echo // modules/rules.h
    echo // Auto-generated master header that includes all conversion rule data
    echo // Generated by build_rules.bat
    echo.
    echo #ifndef RULES_H
    echo #define RULES_H
    echo.
    for %%f in (rules\converter\*.json) do (
        echo #include "%%~nf_rules.h"
    )
    echo.
    echo #endif // RULES_H
) > modules\rules.h

echo.
echo Done! Generated headers:
dir /b modules\*_rules.h modules\rules.h

echo.
echo Now compile with: gcc -DUSE_EMBEDDED_RULES ccal.c modules/converter.c -o ccal.exe
